### ISSUE TITLE
Replace ml-curve-fitting by ml-levenberg-marquardt

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-fitting#6]
ml-curve-fitting is an old project that is not maintained and should be replaced by:

https://github.com/mljs/levenberg-marquardt

**Comment by jobo322** [comment]
First of all, we need to refactor the functions Gaussian, Lorentzian and the trains and sums of those. Looking for the compatibility with [mljs/lm](https://github.com/mljs/levenberg-marquardt). 

A possible refactor for [sumOfLorentzians function](https://github.com/mljs/optimize-lorentzian/blob/master/src/sumOfLorentzians.js#L10-L26) is:

```
function sumOfLorentzians(p) {
  return t => {
    let nL = p.length / 3;
    let result = 0;
    for (let i = 0; i < nL; i++) {
      let p2 = Math.pow(p[i + nL * 2] / 2, 2);
      let factor = p[i + nL] * p2;
      result += factor / (Math.pow(t - p[i], 2) + p2);
    }
    return result;
  };
}
```
It will return a parameterized function

**Comment by jobo322** [comment]
It's done
