### ISSUE TITLE
Optimize width or optimize fwhm

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-fitting#73]
Just to have a trace of this somewhere:

What are we optimising and why this choice ?

**Comment by lpatiny** [comment]
In the README once we obtain results with fwhm and another time we obtain width. Is this normal ? Correct ?

**Comment by jobo322** [comment]
we are optimizing FWHM in all kind of shapes because the package `ml-peak-shape-generator` only accept FWHM at the moment, in order to avoid the conversion width->FWHM we only optimize FWHM. I did fix the error in the readme
