### ISSUE TITLE
JSON parsing makes types incompatible

### ISSUE THREAD

**Issue by maasencioh** [mljs/spectra-fitting#87]
This copy of the elements is in different places, and because of them, the resulting element is `any`, which loses the type and causes incompatibilities. 
https://github.com/mljs/spectra-fitting/blob/cd4317aa7476edcac8f1226777001cfc598b840f/src/index.ts#L158

**Comment by targos** [comment]
Can you be clearer on the specific incompatibilities it introduces? The return type of the function you linked is specified, so the `any` should not have effects outside of it.

**Comment by targos** [comment]
@maasencioh note that there's a big update happening in https://github.com/mljs/spectra-fitting/pull/86

**Comment by maasencioh** [comment]
The branch is from that fork, that's why I didn't open a PR for the moment

**Comment by jobo322** [comment]
Seems it is done, is it right @maasencioh?

**Comment by maasencioh** [comment]
It looks like that
