### ISSUE TITLE
Optimisation of part of the peak

### ISSUE THREAD

**Issue by lpatiny** [mljs/spectra-fitting#92]
I have the impression that the current implementation does not work well if the full peak is not in the spectrum.

For example I would like to optimise a gaussian but only on a width of 1 SD. We cover only 65% of the peak but there should still be a perfect match. This will be useful for NMR when the peaks are often not well separated (or overlap).

@jobo322 Could you evaluate how it is done currently and add a testcase in which we have only a gaussian to fit with only 1SD of points ?

**Comment by lpatiny** [comment]
This issue is related to https://github.com/mljs/spectra-fitting/issues/79

**Comment by jobo322** [comment]
as I can see 

![image](https://user-images.githubusercontent.com/12143935/182035035-ef58400d-06b2-4a5f-96ed-ef3474d6bb38.png)

seems it works well when only one-half of the shape exists in the input data. is it what you mean?

**Comment by jobo322** [comment]
it is almost a perfect match with a parameter error of 1e-8

**Comment by lpatiny** [comment]
Perfect thanks.
