### ISSUE TITLE
output peak structure diffier from output of ml-gsd/optimizePeaks

### ISSUE THREAD

**Issue by jobo322** [mljs/spectra-fitting#93]
There is not a homogenous output between [ml-gsd/optimizePeaks](https://github.com/mljs/global-spectral-deconvolution/blob/master/src/post/optimizePeaksWithLogs.ts) and ml-spectra-fitting.

- ml-gsd
```js
interface GSDPeakOptimized {
  x: number;
  y: number;
  width: number;
  shape: Shape1D;
}
```
- ml-spectra-fitting
```js
interface OptimizedPeak {
  x: number;
  y: number;
  shape: Shape1D;
}
```
@lpatiny @targos should one of these structures persist?

**Comment by lpatiny** [comment]
I think the optimization deals with FWHM and not width.

https://github.com/mljs/global-spectral-deconvolution/blob/394870e5154eaa4e4252fe99e7ffca76d7e9eaed/src/post/__tests__/optimizePeaks.test.ts#L30-L40

And the idea is that the `fwhm` is a shape property. width may not exit. I wonder what we should do for NMR. Just also use fwhm ? For gaussian it is the same. We can always calculate on the fly width if we need.

**Comment by jobo322** [comment]
at the level of [`optimizePeaks`](https://github.com/mljs/global-spectral-deconvolution/blob/master/src/post/optimizePeaks.ts) the function [`groupPeaks`](https://github.com/mljs/global-spectral-deconvolution/blob/master/src/utils/groupPeaks.ts) we need a `width' property peer peak to group peaks. 

if `width` will be removed from Peak structure, How should we group peaks, by `fwhm` or a default `width` value option?
